# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-20 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_generator', '0005_auto_20180514_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='return_time',
            new_name='arrival_time',
        ),
        migrations.AddField(
            model_name='destination',
            name='days_at_destination',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='starting_location',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
